### ISSUE TITLE
百度开发者工具更新后  echart报错

### ISSUE THREAD

**Issue by chenjian03272** [baidu-smart-app/baidu-smart-app-echarts-demo#2]
index.js:1 not found dynamicLib://echarts_4_7_0/chart
master-worker.js:1 Uncaught (in promise) DOMException: Failed to execute 'importScripts' on 'WorkerGlobalScope': The script at 'http://127.0.0.1:62237/output/__dynamicLib__/echarts_4_7_0/app.js' failed to load.
    at Object.include (file:///C:/Users/Administrator/AppData/Local/Programs/swan-ide-gui/resource…1/app.asar/dist/extensions/simulator/dist/runtime/master-worker.js:1:13565)
    at file:///C:/Users/Administrator/AppData/Roaming/%E7%99%BE%E5%BA%A6%E5%BC%80%…85%E5%B7%A5%E5%85%B7/cli/vendor/swan-core/3.90.29/master/index.js:1:340063
    at new Promise (<anonymous>)
    at e.value (file:///C:/Users/Administrator/AppData/Roaming/%E7%99%BE%E5%BA%A6%E5%BC%80%…85%E5%B7%A5%E5%85%B7/cli/vendor/swan-core/3.90.29/master/index.js:1:339989)
    at file:///C:/Users/Administrator/AppData/Roaming/%E7%99%BE%E5%BA%A6%E5%BC%80%…85%E5%B7%A5%E5%85%B7/cli/vendor/swan-core/3.90.29/master/index.js:1:356595
    at Array.map (<anonymous>)
    at e.value (file:///C:/Users/Administrator/AppData/Roaming/%E7%99%BE%E5%BA%A6%E5%BC%80%…85%E5%B7%A5%E5%85%B7/cli/vendor/swan-core/3.90.29/master/index.js:1:356563)
    at file:///C:/Users/Administrator/AppData/Roaming/%E7%99%BE%E5%BA%A6%E5%BC%80%…85%E5%B7%A5%E5%85%B7/cli/vendor/swan-core/3.90.29/master/index.js:1:355373

**Comment by Ovilia** [comment]
是指旧版本的开发者工具没问题，更新了工具后报错的？请问前后的工具版本分别是什么呢？

**Comment by Ovilia** [comment]
长时间没有得到回复，关闭本 issue。
